---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    container_name: zookeeper 
    ports:
      - "2181:2181"
    networks:
      - vdx-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-broker:
    image: confluentinc/cp-kafka
    hostname: kafka-broker
    container_name: kafka-broker 
    ports:
      - "9092:9092"
    networks:
      - vdx-network
    links:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092
  schema-registry:
    image: confluentinc/cp-schema-registry
    hostname: schema-registry
    container_name: schema-registry 
    links:
      - zookeeper
      - kafka-broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
  kafka-rest:
    image: confluentinc/cp-kafka-rest
    hostname: kafka-rest
    container_name: kafka-rest
    ports:
      - "8082:8082"
    networks:
      - vdx-network
    links:
      - zookeeper
      - kafka-broker
      - schema-registry
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KAFKA_REST_LISTENERS: http://kafka-rest:8082
  oracle-db:
    image: carloscastillo/rgt-oracle-xe-11g
    hostname: oracle-db
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "15080:8080"
    networks:
      - vdx-network
    environment:
     - processes=200
     - SCHEMAS=VDX VDX_BATCH OBSIDIAN
     - BATCH_PARAMS=World
    volumes:
     - .db_scripts:/u01/scripts/batch
     - .db_data:/u01/app/oracle

networks:
    vdx-network:
        driver: bridge
